definitions:
  v1.ResBody:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/v1/homework:
    get:
      parameters:
      - description: 跳过的数量
        in: query
        name: offset
        required: true
        type: integer
      - description: 一页返回的数量
        in: query
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"count":1,"homeworks":[{"homework_id":1,"belong_class":1,"creator_id":33,"title":"软件工程第一次测试1","creator":"牛莉","create_time":"2019-11-10T13:54:12+08:00","start_time":"2019-11-10T13:54:12+08:00","end_time":"2019-11-10T13:54:12+08:00"},null]},"massage":"ok"}'
          schema:
            $ref: '#/definitions/v1.ResBody'
      summary: 教师端或是学生端获取作业列表
  /api/v1/login:
    post:
      parameters:
      - description: 用户学号
        in: body
        name: account_id
        required: true
        schema:
          type: integer
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":nil,"msg":"ok"}'
          schema:
            $ref: '#/definitions/v1.ResBody'
        "10002":
          description: '{"code":10002,"data":nil,"msg":"用户不存在"}'
          schema:
            $ref: '#/definitions/v1.ResBody'
        "10003":
          description: '{"code":10003,"data":nil,"msg":"密码错误"}'
          schema:
            $ref: '#/definitions/v1.ResBody'
      summary: 用户登录
  /api/v1/register:
    post:
      parameters:
      - description: 用户学号
        in: body
        name: user_id
        required: true
        schema:
          type: integer
      - description: 姓名
        in: body
        name: real_name
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: 软件工程
        in: body
        name: major
        required: true
        schema:
          type: string
      - description: 年级
        in: body
        name: level
        required: true
        schema:
          type: integer
      - description: 用户类型
        in: body
        name: u_type
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":nil,"msg":"ok"}'
          schema:
            $ref: '#/definitions/v1.ResBody'
        "400":
          description: '{"code":400,"data":nil,"msg":"请求参数错误"}'
          schema:
            $ref: '#/definitions/v1.ResBody'
        "500":
          description: '{"code":500,"data":nil,"msg":"系统错误"}'
          schema:
            $ref: '#/definitions/v1.ResBody'
        "10001":
          description: '{"code":10001,"data":nil,"msg":"该用户已注册"}'
          schema:
            $ref: '#/definitions/v1.ResBody'
      summary: 用户注册
swagger: "2.0"
